import { FormEvent, useEffect, useRef, useState } from "react";
import { login, logout, register, type Player } from "./api/game";
import { World } from "./game/World";

type Mode = "login" | "register";
type RoomPlayer = { playerId: string; position: { x: number; y: number; z: number } };
type RoomEvent = { type: "room_state"; players: RoomPlayer[] } | { type: "player_joined" | "player_moved"; player: RoomPlayer } | { type: "player_left"; playerId: string };
const storageKeys = { access: "openworld.access", refresh: "openworld.refresh", player: "openworld.player" };

export default function App() {
  const [player, setPlayer] = useState<Player | null>(() => { const saved = localStorage.getItem(storageKeys.player); if (!saved) return null; const parsed = JSON.parse(saved) as Player; return parsed.username ? parsed : null; });
  const [mode, setMode] = useState<Mode>("login");
  const [status, setStatus] = useState("Sign in to explore");
  const worldRef = useRef<HTMLDivElement>(null); const world = useRef<World | null>(null);
  function storeAuth(result: { access: string; refresh: string; player: Player }) { localStorage.setItem(storageKeys.access, result.access); localStorage.setItem(storageKeys.refresh, result.refresh); localStorage.setItem(storageKeys.player, JSON.stringify(result.player)); setPlayer(result.player); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { setStatus("Authenticating…"); if (mode === "register") storeAuth(await register(form)); else storeAuth(await login(String(form.get("username")), String(form.get("password")))); } catch (error) { setStatus(error instanceof Error ? error.message : "Authentication failed"); } }
  async function leave() { const access = localStorage.getItem(storageKeys.access); const refresh = localStorage.getItem(storageKeys.refresh); if (access && refresh) await logout(access, refresh); Object.values(storageKeys).forEach(key => localStorage.removeItem(key)); setPlayer(null); setStatus("Signed out"); }
  useEffect(() => { if (!player || !worldRef.current) return; const token = localStorage.getItem(storageKeys.access); if (!token) { setPlayer(null); return; } const protocol = location.protocol === "https:" ? "wss" : "ws"; const socket = new WebSocket(`${protocol}://${location.hostname}:8000/ws/game/rooms/demo/?token=${encodeURIComponent(token)}`); world.current = new World(worldRef.current, position => { if (socket.readyState === WebSocket.OPEN) socket.send(JSON.stringify({ type: "move", position })); }); socket.onopen = () => setStatus("Starter Island — online"); socket.onmessage = ({ data }) => { const event: RoomEvent = JSON.parse(data); const ownId = String(player.id); if (event.type === "room_state") event.players.filter(remote => remote.playerId !== ownId).forEach(remote => world.current?.upsertRemote(remote.playerId, remote)); else if (event.type === "player_left") world.current?.removeRemote(event.playerId); else if (event.player.playerId !== ownId) world.current?.upsertRemote(event.player.playerId, event.player); }; socket.onclose = () => setStatus("Room connection lost"); return () => { socket.close(); world.current?.dispose(); world.current = null; }; }, [player]);
  if (!player) return <main className="welcome"><section><p className="eyebrow">OPENWORLD</p><h1>Starter Island</h1><p>Create an explorer or sign back in.</p><div className="tabs"><button className={mode === "login" ? "selected" : ""} type="button" onClick={() => setMode("login")}>Login</button><button className={mode === "register" ? "selected" : ""} type="button" onClick={() => setMode("register")}>Register</button></div><form onSubmit={submit}><label>Username<input name="username" minLength={1} maxLength={150} required autoFocus /></label>{mode === "register" && <><label>Display name<input name="display_name" maxLength={24} placeholder="Explorer" /></label><label>Avatar<input name="avatar" type="file" accept="image/*" /></label></>}<label>Password<input name="password" type="password" minLength={8} required /></label>{mode === "register" && <label>Confirm password<input name="password_confirmation" type="password" minLength={8} required /></label>}<button>{mode === "login" ? "Enter world" : "Create explorer"}</button></form><small>{status}</small></section></main>;
  return <main className="game"><div ref={worldRef} className="canvas" /><aside>{player.avatar && <img src={player.avatar} alt="" />}<strong>{player.display_name || player.username}</strong><span>@{player.username}</span><span>{status}</span><span>WASD to move · drag to orbit</span><button type="button" onClick={leave}>Sign out</button></aside></main>;
}
